### ISSUE TITLE
[BUG] Build Error

### ISSUE THREAD

**Issue by sclel016** [NobodyXu/swaystatus#32]
**Description**
Compiler error when trying to build master(dc196ef8) on Fedora 34.

**To Reproduce**
1. Clone Repository to system running Fedora 34
2. `cd swaystatus/src`
3. `make -j4`

**Expected behavior**
Build should complete without errors.

**Actual behavior**
```
handle_click_events.cc:83:40: error: use of undeclared identifier 'JSON_TOKENER_ALLOW_TRAILING_CHARS'
        json_tokener_set_flags(parser, JSON_TOKENER_ALLOW_TRAILING_CHARS);

```

**Desktop:**
 - Fedora 34
 - `swaystatus` version: Latest
 - `json-c-devel`: 0.14-8.fc34

**Comment by NobodyXu** [comment]
I have removed the use of this flag in main a4f28b9a3e15238177ec5ffadca9ea721513ce7d, now it should compile without any error.

**Comment by sclel016** [comment]
Works now, thanks!

**Comment by NobodyXu** [comment]
No worries.

A new release 0.3.1 is created that fixed this issue.
