### ISSUE TITLE
Where do I put the config file?

### ISSUE THREAD

**Issue by Inoshy** [NobodyXu/swaystatus#49]
Where to put the config file and what should be its naming/location. thanks.

**Comment by NobodyXu** [comment]
You can put it anyway you want as long as that path is accessible.

swaystatus accepts the path to the config as a cmdline argument, if it is not present, then it will use its builtin configuration.

I personally put it under $HOME/.config/sway/swaystatus_config.json, since it is a sway related configuration.

**Comment by Inoshy** [comment]
Thank you so much! it works just fine!
I am amazed by its performance. It uses 5~6 times **less** memory and cpu than alternatives like waybar that I tried before it, and the bash script i wrote that suddenly spikes from 0 to some percentage of cpu.

**Comment by NobodyXu** [comment]
One of the reason why I implements swaystatus is that bash scripts usually spawn many processes per second, including date, echo, etc, and the alternative waybar is quite big and hard to compile while it seems that it doesn’t get rid of process spawning altogether.

So I write swaystatus, deciding to remove process spawning completely while keeping it simple, that’s why I choose to use formatting library fmt, which is type safe and lightweight.

**Comment by Inoshy** [comment]
I wish your great work becomes mainstream among sway users! keeping up with a thankless job is hard, yet you are doing it. thanks for all this.

**Comment by NobodyXu** [comment]
To be honest, I will be more than happy if there are contributors to this project, since I often made bad design and don’t have a ton of time adding new features (especially during the end of the year), I would appreciate any help.

**Comment by NobodyXu** [comment]
Since the issue itself is solved, I am going to close this issue.
If you have any other questions, feel free to open another issue or discuss about this project on the discussion.

And thank you again for your compliment!
